<a href="https://colab.research.google.com/github/poonamkhot123/Array-s-python-code/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1: Transpose Array
Given a 2D NumPy array arr_2d, transpose the array and print the result.

Example Input:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

Example Output:
Transposed Array: [[1 4] [2 5] [3 6]]

In [ ]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Transposed Array:", arr_2d.T)


Transposed Array: [[1 4]
 [2 5]
 [3 6]]


Question 2: Reshape Array
Given a 1D NumPy array arr_1d, reshape it into a 3x2 array and print the result.

Example Input:
arr_1d = np.array([1, 2, 3, 4, 5, 6])

Example Output:
Reshaped Array: [[1 2] [3 4] [5 6]]

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
print("Reshaped Array:", arr.reshape(3, 2))


Reshaped Array: [[1 2]
 [3 4]
 [5 6]]


Question 3: Resize Array
Given a 1D NumPy array arr_1d, resize it into a 3x3 array and print the result.

Example Input:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

Example Output:
Resized Array: [[1 2 3] [4 5 6] [7 8 1]]

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("Resized Array:", np.resize(arr, (3, 3)))

Resized Array: [[1 2 3]
 [4 5 6]
 [7 8 1]]


Question 4: Flatten Array
Given a 2D NumPy array arr_2d, flatten it and print the result.

Example Input:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

Example Output:
Flattened Array: [1 2 3 4 5 6]

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.flatten())


[1 2 3 4 5 6]


Question 5: Transpose Array
Given a 3D NumPy array arr_3d, transpose the array and print the result.
Example Input:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
Example Output:
Transposed Array: [[[ 1 5 9] [ 2 6 10]]
[[ 3 7 11] [ 4 8 12]]]

In [ ]:
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(arr.transpose(1, 2, 0))

[[[ 1  5  9]
  [ 2  6 10]]

 [[ 3  7 11]
  [ 4  8 12]]]


Question 6: Reshape Array
Given a 1D NumPy array arr_1d, reshape it into a 4x3 array and print the result.

Example Input:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

Example Output:
Reshaped Array: [[ 1 2 3] [ 4 5 6] [ 7 8 9] [10 11 12]]


In [ ]:
import numpy as np
arr = np.arange(1, 13).reshape(4, 3)
print(arr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Question 7: Resize Array
Given a 2D NumPy array arr_2d, resize it into a 4x4 array and print the result.

Example Input:
arr_2d = np.array([[1, 2], [3, 4]])

Example Output:
Resized Array: [[1 2 1 2] [3 4 3 4] [1 2 1 2] [3 4 3 4]]


In [ ]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(np.tile(arr, (2, 2)))


[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


Question 8: Flatten Array
Given a 3D NumPy array arr_3d, flatten it and print the result.

Example Input:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

Example Output:
Flattened Array: [1 2 3 4 5 6 7 8]

In [ ]:
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr.ravel())


[1 2 3 4 5 6 7 8]
